### ISSUE TITLE
Bootanimation.mp4 file not found

### ISSUE THREAD

**Issue by ky960310** [sudo-monkey/proton-x50-boot-animation#4]
Hello there, some silly questions if you don't mind. 

Your step mentioned:

1) Copy all the files into a usb pendrive. Should I include the bootanimation.mp4 files you provided? Because it is proton original start up animation.

2) add .mp4 videos
I've created my own mp4 video,what file name should I rename to? How long is the video length you recommend? Is 15 seconds ok?
Please advise 🙏 

So total 5 files include my own mo4 video which are B832bc614xxx, readme.md, bootanimation.mp4, my own mp4 and done.sh ?

Looking forward to your reply🙏 thanks man.

**Comment by k8smonkey** [comment]
1. No, replace the file with your own. The file for sample only. 

2. Rename your file to bootanimation.mp4

3. Yeah. 15 seconds would be good. Boot startup time are varies according to the IHU state, sometimes fast, sometimes slow. So it takes try and error.

**Comment by ky960310** [comment]
> 1. No, replace the file with your own. The file for sample only. 
> 
> 2. Rename your file to bootanimation.mp4
> 
> 3. Yeah. 15 seconds would be good. Boot startup time are varies according to the IHU state, sometimes fast, sometimes slow. So it takes try and error.

Hello good morning.
I just tried the script this morning but it's not successful. The output log file said No such file or directory. Pls advise, thanks ![image](https://github.com/sudo-monkey/proton-x50-boot-animation/assets/131019179/211e5796-7cbe-4ec2-a220-b6ae961b2dee)

**Comment by JayChong12** [comment]
It's ok for file like this? Just replace my own video. This all file is for atlas version right?

![image](https://github.com/sudo-monkey/proton-x50-boot-animation/assets/145475113/5c99c27a-f18d-4aad-9aa1-c89233a4eb14)

**Comment by ky960310** [comment]
> > 1. No, replace the file with your own. The file for sample only. 
> > 
> > 2. Rename your file to bootanimation.mp4
> > 
> > 3. Yeah. 15 seconds would be good. Boot startup time are varies according to the IHU state, sometimes fast, sometimes slow. So it takes try and error.
> 
> Hello good morning.
> I just tried the script this morning but it's not successful. The output log file said No such file or directory. Pls advise, thanks ![image](https://github.com/sudo-monkey/proton-x50-boot-animation/assets/131019179/211e5796-7cbe-4ec2-a220-b6ae961b2dee)

I tried many times still unsuccessful. It automatically jump to the hidden setting and it won't restart the ihu also... My ihu is atlas 617.

**Comment by k8smonkey** [comment]
I have a feeling u double formatted the mp4 file.

"bootanimation" is the filename and .mp4 is the file extension. However it is possible that you actually put the name of your file as "bootanimation.mp4" and the system will interpret it as "bootanimation.mp4".mp4 hence the file cannot be found. 

Perhaps try renaming your file to "bootanimation". As long it's an mp4 video it should works.

**Comment by ky960310** [comment]
> I have a feeling u double formatted the mp4 file.
> 
> "bootanimation" is the filename and .mp4 is the file extension. However it is possible that you actually put the name of your file as "bootanimation.mp4" and the system will interpret it as "bootanimation.mp4".mp4 hence the file cannot be found. 
> 
> Perhaps try renaming your file to "bootanimation". As long it's an mp4 video it should works. 

Hi sudo monkey! I found out the problem already! The mp4 file name just need to change it to bootanimation. Thanks man! Much appreciate your hard work! https://github.com/sudo-monkey/proton-x50-boot-animation/assets/131019179/b6cb4d07-6e31-4138-b5da-6b31e1a0a780

**Comment by k8smonkey** [comment]
> appreciate

You are welcome. 👍
